### ISSUE TITLE
Global var and function bug

### ISSUE THREAD

**Issue by mingwya** [bmx-ng/bmx-ng#105] opened 2019-11-28 00:47 UTC
'This code:

SuperStrict

Global ar$[]

Function Add(s$, array$[])
	array:+[s]
End Function

Add("Hello!",ar)
Add("Albert!",ar)

For Local i% = 0 Until ar.Length
	Print ar[i]
Next
Print ar.Length

'---
'output 0

**Comment by HurryStarfish** [comment] 2019-11-28 01:03
That's not a bug. Behaviour is the same as in BlitzMax vanilla.
`array :+ [s]` is equivalent to `array = array + [s]`. You're creating a new array and assigning it to the `array` variable. This does not modify the `ar` variable you passed to the function. If you want it to do that, you gotta declare the parameter as pass-by-reference: `Function Add(s$, array$[] Var)`

**Comment by mingwya** [comment] 2019-11-28 01:37
thanks!

**Comment by GWRon** [comment] 2022-10-31 09:29
Can you please close the issue?

**Closed** 2022-10-31 19:27 UTC
