### ISSUE TITLE
"sys/sysctl.h: No such file or directory" on Manjaro Linux x64 on first run

### ISSUE THREAD

**Issue by elliotwutingfeng** [bmx-ng/bmx-ng#140] opened 2022-06-06 08:19 UTC
**Describe the bug**
After extracting the tarball and running MaxIDE for the first time, when attempting to build a hello world program `Print "Hello World!"`, the build will fail with the error message `sys/sysctl.h: No such file or directory`. This can be fixed with a workaround described below

**To Reproduce**
- Download and extract tarball from https://blitzmax.org/downloads/
- Run MaxIDE
- Create New File with **Ctrl+N**
- Type `Print "Hello World!"` into **untitled1.bmx**
- Build with **Ctrl+B**
- The build fails with error `sys/sysctl.h: No such file or directory`, **glue.c** is automatically opened, pointing to line 24 `#include <sys/sysctl.h>`.

**Workaround**
- Delete `#include <sys/sysctl.h>` from **glue.c**, save the file.
- Run build (**Ctrl+B**) on **untitled1.bmx**, the build should succeed.
- Paste back `#include <sys/sysctl.h>` into **glue.c**, save the file.
- Run build (**Ctrl+B**) on **untitled1.bmx**, the build should succeed even though `#include <sys/sysctl.h>` is back in **glue.c**.

**Expected behavior**
The build should succeed for the first time without needing the workaround.

**Screenshots**
n/a

**Version information (please complete the following information):**
 - OS: Manjaro Linux x64 GNOME Kernel 5.15.41-1-MANJARO
 - maxide 1.56

**Additional context**

**Comment by GWRon** [comment] 2022-06-06 10:55
Duplicate of https://github.com/bmx-ng/brl.mod/issues/232

**Closed** 2022-06-09 21:03 UTC
